config/routes.rb
Rails.application.routes.draw do
  
  resources :parties
  get 'sessions/new'

  get '/home' => 'home#index'
  
  get '/ranking' => 'ranking#index'
  get '/curtidas' => 'ranking#loadGraphic'
  get '/espectro' => 'users#politicSpectre'
  get 'ranking/data', :defaults => { :format => 'json' }

  post '/like' => 'acceptances#acceptancesInterceptor'
  post '/update-comment' => 'comments#updateComment'

  post '/generate-colors' => 'ranking#generateColorsToSequencesGraph'

  root 'home#index'

  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  get '/projeto' => 'home#o_projeto'
  get '/projeto/esquerda-direita' => 'home#esquerda_direita'
  get '/projeto/espectro-politico' => 'home#espectro_politico'

  get '/projetos-de-lei' => 'law_projects#index'
  get '/deputados' => 'politicians#index'

  get '/alterar-senha' => 'users#show_change_password'
  post '/change-password' => 'users#change_password'

  resources :comments
  resources :acceptances
  resources :interactions
  resources :notices
  resources :experiences
  resources :states
  resources :charges
  resources :politicians
  resources :law_projects
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/party.rb
class Party < ApplicationRecord
	has_many :politicians, through: :politicians

	def social_orientation
		
	end

	def economic_orientation
		
	end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :filterAccess, except: [:index, :show]
  before_action :load_ideologies, only: [:new, :edit]
  before_action :set_party, only: [:show, :edit, :update, :destroy]

  # GET /parties
  # GET /parties.json
  def index
    @parties = Party.all
  end

  # GET /parties/1
  # GET /parties/1.json
  def show
  end

  # GET /parties/new
  def new
    @party = Party.new
  end

  # GET /parties/1/edit
  def edit
  end

  # POST /parties
  # POST /parties.json
  def create
    
    @party = Party.new
    @party.name = party_params[:name]
    @party.orientation = party_params[:economic_orientation] + ' ' + party_params[:social_orientation]

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render :show, status: :created, location: @party }
      else
        format.html { render :new }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parties/1
  # PATCH/PUT /parties/1.json
  def update
    respond_to do |format|
      if @party.update(party_params)
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { render :show, status: :ok, location: @party }
      else
        format.html { render :edit }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party.destroy
    respond_to do |format|
      format.html { redirect_to parties_url, notice: 'Party was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def filterAccess
    redirect_to "/" unless (!current_user.nil? && isAdmin?)
  end

  def load_ideologies
    @economicIdeologies = ['DIREITA CENTRALIZADA', 'DIREITA MODERADA', 'DIREITA EXTREMA', 'ESQUERDA CENTRALIZADA', 'ESQUERDA MODERADA', 'ESQUERDA EXTREMA' ]
    @socialIdeologies = ['AUTORITARIO CENTRALIZADA', 'AUTORITARIO MODERADA', 'AUTORITARIO EXTREMA', 'LIBERTARIO CENTRALIZADA', 'LIBERTARIO MODERADA', 'LIBERTARIO EXTREMA' ]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_party
      @party = Party.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def party_params
      params.require(:party).permit(:name, :orientation, :social_orientation, :economic_orientation)
    end
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/parties/_form.html.erb
<div class="container">
  <%= form_with(model: party, local: true) do |form| %>
    <% if party.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(party.errors.count, "error") %> prohibited this party from being saved:</h2>

        <ul>
        <% party.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="col-md-4">
        <div class="form-group">
          <%= form.label :name, 'Nome' %>
          <%= form.text_field :name, id: :party_name, class: 'form-control' %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <div class="form-group">
          <%= form.label :economic_orientation, 'Influência do Estado na economia' %>
          <%= select(:party, :economic_orientation, @economicIdeologies, {prompt: 'Selecione a orientação'}, {class: 'form-control'} ) %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <div class="form-group">
          <%= form.label :social_orientation, 'Influência do Estado no social' %>
          <%= select(:party, :social_orientation, @socialIdeologies, {prompt: 'Selecione a orientação'}, {class: 'form-control'} ) %>
        </div>
      </div>
    </div><br />

    <div class="actions">
      <%= form.submit "Salvar", class: 'btn btn-primary'%>
    </div>
  <% end %>
</div>

app/views/parties/edit.html.erb
<div class="container">
	<h1>Editar partido</h1><br />

	<%= render 'form', party: @party %>
</div>

app/views/parties/index.html.erb
<div class="container">

  <h1>Partidos</h1><br />

  <table id="parties-table" class="table table-hover table-responsible">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Ideologia política</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @parties.each do |party| %>
        <tr>
          <td><%= party.name %></td>
          <td><%= party.orientation %></td>
          <td><%= link_to 'Visualizar', party %></td>
          <td><%= link_to 'Editar dados', edit_party_path(party)%></td>
          <td>
            <%= button_to party, class: 'btn btn-primary', method: :delete, data: { confirm: 'Are you sure?' }  do %>
              <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            <%end%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= button_to '+ Novo partido', new_party_path, class: 'btn btn-primary', method: :get %>
</div>

app/views/parties/new.html.erb
<div class="container">
	<h1>Cadastro de partidos</h1><br />

	<%= render 'form', party: @party %>

	<%= link_to 'Voltar', parties_path %>

</div>

app/views/parties/show.html.erb
<div class="container">

<p>
  <strong>Nome:</strong>
  <%= @party.name %>
</p>

<p>
  <strong>Orientação:</strong>
  <%= @party.orientation %>
</p>

</div>