config/routes.rb
Rails.application.routes.draw do
  
  resources :parties
  get 'sessions/new'

  get '/home' => 'home#index'
  
  get '/ranking' => 'ranking#index'
  get '/curtidas' => 'ranking#loadGraphic'
  get '/espectro' => 'users#politicSpectre'
  get 'ranking/data', :defaults => { :format => 'json' }

  post '/like' => 'acceptances#acceptancesInterceptor'
  post '/update-comment' => 'comments#updateComment'

  post '/generate-colors' => 'ranking#generateColorsToSequencesGraph'

  root 'home#index'

  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  get '/projeto' => 'home#o_projeto'
  get '/projeto/esquerda-direita' => 'home#esquerda_direita'
  get '/projeto/espectro-politico' => 'home#espectro_politico'

  get '/projetos-de-lei' => 'law_projects#index'
  get '/deputados' => 'politicians#index'

  get '/alterar-senha' => 'users#show_change_password'
  post '/change-password' => 'users#change_password'

  resources :comments
  resources :acceptances
  resources :interactions
  resources :notices
  resources :experiences
  resources :states
  resources :charges
  resources :politicians
  resources :law_projects
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/acceptance.rb
class Acceptance < ApplicationRecord
	belongs_to :interaction

	validates_inclusion_of :like, :in => [true, false]
end

app/controllers/acceptances_controller.rb
class AcceptancesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_acceptance, only: [:show, :edit, :update, :destroy]

  # GET /acceptances
  # GET /acceptances.json
  def index
    @acceptances = Acceptance.all
  end

  # GET /acceptances/1
  # GET /acceptances/1.json
  def show
  end

  # GET /acceptances/new
  def new
    @acceptance = Acceptance.new
  end

  # GET /acceptances/1/edit
  def edit
  end

  def acceptancesInterceptor
  
    if current_user

      if (!check_acceptance_existent)

        acceptance = Acceptance.new
        create_interaction_acceptance

        acceptance.like = params[:like]
        acceptance.interaction = @interaction

        acceptance.save
        
      else
        
        if params[:to_delete].nil?
          
          if @loadedAcceptance.first.like
            Acceptance.update(@loadedAcceptance.first.id, like: false)
          else
            Acceptance.update(@loadedAcceptance.first.id, like: true) 
          end

        else
          Acceptance.destroy(@loadedAcceptance.first.id)
          Interaction.destroy(@loadedAcceptance.first.interaction_id)
        end
        
      end
    end
  end
  # POST /acceptances
  # POST /acceptances.json
  def create
    @acceptance = Acceptance.new(acceptance_params)

    respond_to do |format|
      if @acceptance.save
        format.html { redirect_to @acceptance, notice: 'Acceptance was successfully created.' }
        format.json { render :show, status: :created, location: @acceptance }
      else
        format.html { render :new }
        format.json { render json: @acceptance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acceptances/1
  # PATCH/PUT /acceptances/1.json
  def update
    respond_to do |format|
      if @acceptance.update(acceptance_params)
        format.html { redirect_to @acceptance, notice: 'Acceptance was successfully updated.' }
        format.json { render :show, status: :ok, location: @acceptance }
      else
        format.html { render :edit }
        format.json { render json: @acceptance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acceptances/1
  # DELETE /acceptances/1.json
  def destroy
    @acceptance.destroy
    respond_to do |format|
      format.html { redirect_to acceptances_url, notice: 'Acceptance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def check_acceptance_existent
  
    interactions = Interaction.where(user_id: current_user.id, law_project_id: params[:law_project])

    if interactions.blank?
      return false
    else
      
      interactions.each do |i|
        
        if ((!i.acceptance.nil?) && (i.law_project_id.eql?(params[:law_project].to_i)))
          @acceptanceInteraction = i
        end
      end
      
      if @acceptanceInteraction.nil?
        return false
      else
        @loadedAcceptance = Acceptance.where(interaction_id: @acceptanceInteraction)
      end
      
    end
    
    if @loadedAcceptance.blank?
      return false
    else
      return true
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_acceptance
      @acceptance = Acceptance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def acceptance_params
      params.require(:acceptance).permit(:like)
    end
end

app/helpers/acceptances_helper.rb
module AcceptancesHelper
end

app/views/acceptances/_form.html.erb
<%= form_with(model: acceptance, local: true) do |form| %>
  <% if acceptance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(acceptance.errors.count, "error") %> prohibited this acceptance from being saved:</h2>

      <ul>
      <% acceptance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :like %>
    <%= form.check_box :like, id: :acceptance_like %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/acceptances/edit.html.erb
<h1>Editing Acceptance</h1>

<%= render 'form', acceptance: @acceptance %>

<%= link_to 'Show', @acceptance %> |
<%= link_to 'Back', acceptances_path %>

app/views/acceptances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Acceptances</h1>

<table>
  <thead>
    <tr>
      <th>Like</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @acceptances.each do |acceptance| %>
      <tr>
        <td><%= acceptance.like %></td>
        <td><%= link_to 'Show', acceptance %></td>
        <td><%= link_to 'Edit', edit_acceptance_path(acceptance) %></td>
        <td><%= link_to 'Destroy', acceptance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Acceptance', new_acceptance_path %>

app/views/acceptances/new.html.erb
<h1>New Acceptance</h1>

<%= render 'form', acceptance: @acceptance %>

<%= link_to 'Back', acceptances_path %>

app/views/acceptances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Like:</strong>
  <%= @acceptance.like %>
</p>

<%= link_to 'Edit', edit_acceptance_path(@acceptance) %> |
<%= link_to 'Back', acceptances_path %>