config/routes.rb
Rails.application.routes.draw do
  
  resources :parties
  get 'sessions/new'

  get '/home' => 'home#index'
  
  get '/ranking' => 'ranking#index'
  get '/curtidas' => 'ranking#loadGraphic'
  get '/espectro' => 'users#politicSpectre'
  get 'ranking/data', :defaults => { :format => 'json' }

  post '/like' => 'acceptances#acceptancesInterceptor'
  post '/update-comment' => 'comments#updateComment'

  post '/generate-colors' => 'ranking#generateColorsToSequencesGraph'

  root 'home#index'

  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  get '/projeto' => 'home#o_projeto'
  get '/projeto/esquerda-direita' => 'home#esquerda_direita'
  get '/projeto/espectro-politico' => 'home#espectro_politico'

  get '/projetos-de-lei' => 'law_projects#index'
  get '/deputados' => 'politicians#index'

  get '/alterar-senha' => 'users#show_change_password'
  post '/change-password' => 'users#change_password'

  resources :comments
  resources :acceptances
  resources :interactions
  resources :notices
  resources :experiences
  resources :states
  resources :charges
  resources :politicians
  resources :law_projects
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/law_project.rb
class LawProject < ApplicationRecord
	has_many :interactions
    has_many :politician_laws
    has_many :politicians, through: :politician_laws
    has_many :comments, through: :interactions
    has_many :acceptances, through: :interactions
    
    validates :law_number, presence:true
    validates :description, presence:true
    validates :date, presence:true

    def countAcceptances
        
    	allAcceptances = Acceptance.all
        lawProjectCount = Hash.new

        startHash = {
            :acceptances => {:like => 0, :dislike => 0}
        }

        lawProjectCount.store(self.id, startHash)

        allAcceptances.each do |a|

            if (a.interaction.law_project.id.eql?(self.id))
                lawProjectCount = incrementAcceptance(a, lawProjectCount)    
            end 
            
        end

        return lawProjectCount
        
    end

    def incrementAcceptance(acceptance, hash)

        lawProjectId = acceptance.interaction.law_project.id
        valueLike = hash[lawProjectId][:acceptances][:like]
        valueDislike = hash[lawProjectId][:acceptances][:dislike]

        if acceptance.like
           hash[lawProjectId][:acceptances][:like] = valueLike+=1
        else
           hash[lawProjectId][:acceptances][:dislike] = valueDislike+=1 
        end

        return hash
    end
end

app/controllers/law_projects_controller.rb
class LawProjectsController < ApplicationController
  before_action :filterAccess, except: [:index, :show]
  before_action :set_law_project, only: [:show, :edit, :update, :destroy]

  # GET /law_projects
  # GET /law_projects.json
  def index
    @law_projects = LawProject.all
    
    render 'users_index' if ((logged_in? && !isAdmin?) || (!logged_in?))
    
  end

  # GET /law_projects/1
  # GET /law_projects/1.json
  def show
    @acceptance_project = Acceptance.new
    @comment_form = Comment.new
    load_all_comments(params['id'])
    load_all_acceptances(params['id'])

    if (logged_in? && (!@all_acceptances.empty?))
      load_user_acceptance
    end
  end

  # GET /law_projects/new
  def new
    @law_project = LawProject.new
  end

  # GET /law_projects/1/edit
  def edit
  end

  # POST /law_projects
  # POST /law_projects.json
  def create
    @law_project = LawProject.new(law_project_params)

    respond_to do |format|
      if @law_project.save
        format.html { redirect_to law_projects_path, notice: 'Law project was successfully created.' }
        format.json { render :show, status: :created, location: @law_project }
      else
        format.html { render :new }
        format.json { render json: @law_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /law_projects/1
  # PATCH/PUT /law_projects/1.json
  def update
    respond_to do |format|
      if @law_project.update(law_project_params)
        format.html { redirect_to @law_project, notice: 'Law project was successfully updated.' }
        format.json { render :show, status: :ok, location: @law_project }
      else
        format.html { render :edit }
        format.json { render json: @law_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /law_projects/1
  # DELETE /law_projects/1.json
  def destroy
    @law_project.interactions.destroy_all
    @law_project.destroy
    respond_to do |format|
      format.html { redirect_to law_projects_url, notice: 'Law project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def filterAccess
    redirect_to "/" unless (!current_user.nil? && isAdmin?)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_law_project
      @law_project = LawProject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def law_project_params
      params.require(:law_project).permit(:law_number, :description, :date, :politician_ids, :abstract)
    end
end

app/helpers/law_projects_helper.rb
module LawProjectsHelper

	def load_politicians
		@politicians = Politician.all
	end

	def create_interaction
		
		@interaction = Interaction.new
		@interaction.user = current_user if logged_in?
		@interaction.law_project_id = params['comment']['law_project_id']
	
		@interaction.save		
	end

	def create_interaction_acceptance
		
		@interaction = Interaction.new
		@interaction.user = current_user if logged_in?
		@interaction.law_project_id = params[:law_project]
		
		@interaction.save
	end

	def load_all_interactions(law_project_id)
		return Interaction.where(law_project_id: law_project_id)
	end

	def load_all_comments(law_project_id)
		comments = load_all_interactions(law_project_id).to_a
		
		@all_comments = []

		comments.each do |c|
			if ((!c.comment.nil?) && (c.acceptance.nil?))
				@all_comments.push(c)
			end
		end
	end

	def load_all_acceptances(law_project_id)
		acceptances = load_all_interactions(law_project_id).to_a
		
		@number_of_likes = 0
		@number_of_dislikes = 0

		@all_acceptances = []
		acceptances.each do |a|
			if ((!a.acceptance.nil?) && (a.comment.nil?))
				@all_acceptances.push(a)
				if (a.acceptance.like == true)
					@number_of_likes +=1
				else
					@number_of_dislikes +=1
				end
			end
		end
	end

	def load_user_acceptance
		
		@all_acceptances.each do |a|
			
			next if (!a.user_id.eql?(current_user.id))
			
			if (a.user_id.eql?(current_user.id))
				@acceptanceUser = a
				break
			end
		end
	end
end

app/views/law_projects/_acceptance_project.html.erb
<%= form_for @acceptance_project, :url => { :controller => "acceptances", :action => "create" }, :html => {:method => :post}, local: true do |form|  %>
  		

  	<!-- NOT WORKING   -->
	<%= form.hidden_field :law_project_id, :value => params['id'] %>
	<%= form.check_box :like, id: :acceptance_like, hidden: :true %>

    <% if logged_in? %>
    	
      <div class="actions">

        <%if (!@acceptanceUser.nil?)%>
          
          <%if (@acceptanceUser.acceptance.like)%>

            <%= link_to 'javascript:;', id: "btn-like", class: "like-strong" do %>
            aprovo <span class="like-icon liked" aria-hidden="true"></span>
            <% end %>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <%= link_to 'javascript:;', id: "btn-dislike" do %>
              não aprovo <span class="dislike-icon" aria-hidden="true"></span>
            <% end %>

          <%else%>

            <%= link_to 'javascript:;', id: "btn-like" do %>
            aprovo <span class="like-icon" aria-hidden="true"></span>
            <% end %>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <%= link_to 'javascript:;', id: "btn-dislike", class: "dislike-strong" do %>
              não aprovo <span class="dislike-icon disliked" aria-hidden="true"></span>
            <% end %>

          <%end%>

        <%else%>

          <%= link_to 'javascript:;', id: "btn-like" do %>
          aprovo <span class="like-icon" aria-hidden="true"></span>
          <% end %>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <%= link_to 'javascript:;', id: "btn-dislike" do %>
            não aprovo <span class="dislike-icon" aria-hidden="true"></span>
          <% end %>  

        <%end%>
    		
        <div>
          <span class="badge badge-like"><%=@number_of_likes%></span>
          <span class="badge badge-dislike"><%=@number_of_dislikes%></span>
        </div>

  	  </div> 

    <%else%>

     <div class="actions">
        <%= link_to '#', id: "btn-like-disabled" do %>
          aprovo <span class="like-icon like-disabled" aria-hidden="true"></span>
        <% end %>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to '#', id: "btn-dislike-disabled" do %>
          não aprovo <span class="dislike-icon dislike-disabled" aria-hidden="true"></span>
        <% end %>     
     </div>

    <div>
      <span class="badge badge-like disabled"><%=@number_of_likes%></span>
      <span class="badge badge-dislike disabled"><%=@number_of_dislikes%></span>
    </div>

   <%end%>
<% end %>
		
		


	

app/views/law_projects/_all_comments.html.erb
<h4>Comentários</h4> <span class="badge comments-number"> <%= @all_comments.size %> </span><hr />
<div class="container">
  <% @all_comments.each do |law_project| %>
    
    <%if !law_project.comment.nil? %>

      <%= form_for law_project.comment, :url => { :controller => "comments", :action => "updateComment" }, :html => {:method => :post, :id => "form-edit-comment"}, local: true do |form|  %>
      
        <%= form.hidden_field :law_project_id, :value => params['id'] %>
        
        <div class="row">
          
          <div class="col-md-8">
            
            <div class="form-group comment-item" data-id="<%=law_project.comment.id.to_s%>">
              
              <h5><%= law_project.comment.interaction.user.name%></h5>
              
              <%= form.text_area :description, id: law_project.comment.id.to_s, class: 'form-control', disabled: :true %> <br />

              <% if (logged_in? && current_user.name.eql?(law_project.comment.interaction.user.name)) %>

                <%= form.hidden_field :comment_id, :value => law_project.comment.id %>        
                
                <%= link_to 'Salvar alterações', '#', id: law_project.comment.id.to_s, class: 'btnSaveComment', :data => {:comment_id => law_project.comment.id.to_s}%>

                <%= link_to 'Editar comentário', 'javascript:;', id: law_project.comment.id.to_s, class: 'btnEditComment' %> &nbsp &nbsp | &nbsp &nbsp

                <%= link_to 'Remover comentário', comment_path(law_project.comment.id), method: :delete %>
              <% end %>
            </div>
          </div>  
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/law_projects/_comment.html.erb
<%= form_for @comment_form, :url => { :controller => "comments", :action => "create" }, :html => {:method => :post}, local: true do |form|  %>
	
  <%= form.hidden_field :law_project_id, :value => params['id'] %>
  
  <div class="row">
    <div class="col-md-8">
      <div class="form-group">
        <h4>Deixe sua opinião sobre este projeto:</h4>
        <% if current_user.nil?%>
          <%= form.text_area :description, id: 'comment-box', class: 'form-control', disabled: :true %>  
          <br />        
          <%= form.submit "Enviar", class: 'btn btn-primary', disabled: :true %> &nbsp Faça login para comentar
        <% else %>
          <%= form.text_area :description, id: 'comment-box', class: 'form-control' %>  
          <br />        
          <%= form.submit "Enviar", class: 'btn btn-primary'%>
        <% end %>    	
      </div>
    </div>    
  </div>
  
<% end %>

app/views/law_projects/_form.html.erb
<%= form_with(model: law_project, local: true) do |form| %>
  <% if law_project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(law_project.errors.count, "error") %> prohibited this law_project from being saved:</h2>

      <ul>
      <% law_project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-2">
      <div class="form-group">
        <%= form.label :law_number, 'Projeto de lei número' %>
        <%= form.number_field :law_number, id: :law_project_law_number, class: 'form-control'  %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <%= form.label :description, 'Texto original do projeto' %>
        <%= form.text_area :description, id: :law_project_description, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <%= form.label :abstract, 'Resumo do projeto' %>
        <%= form.text_area :abstract, id: :law_project_abstract, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <div class="form-group">
        <%= form.label :date, 'Data' %>
        <%= form.text_field :date, id: :law_project_date, type: 'date', class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <div class="form-group">
        <%= form.label 'Autor' %>
        <%= collection_select(:law_project, :politician_ids, load_politicians, :id, :name, {prompt: "Autor do projeto"}, {class: 'form-control'} ) %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit "Salvar", class: 'btn btn-primary'%>
    <%= button_to 'Voltar', law_projects_path, class: 'btn btn-default btn-sm', method: :get%>
  </div>
<% end %>

app/views/law_projects/edit.html.erb
<h1>Editing Law Project</h1>

<div class="container">
	<%= render 'form', law_project: @law_project %>

	<%= link_to 'Show', @law_project %> |
	<%= link_to 'Back', law_projects_path %>
</div>

app/views/law_projects/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

<h2>Projetos de lei</h2><br />

<table class="table table-hover">
  <thead>
    <tr>
      <th>Número</th>
      <th>Autor</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @law_projects.each do |law_project| %>
      <tr>
        <td><%= law_project.law_number %></td>
        <td><%= law_project.politicians.first.name %></td>
        <td><%= law_project.date %></td>
        <td><%= link_to 'Visualizar projeto', law_project %></td>
        <td><%= link_to 'Editar', edit_law_project_path(law_project) %></td>
        <td>
            <%= button_to law_project, class: 'btn btn-primary', method: :delete, data: { confirm: 'Are you sure?' }  do %>
              <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table><br>

<%= button_to '+ Novo projeto de lei', new_law_project_path, class: 'btn btn-primary', method: :get  %>

</div>

app/views/law_projects/new.html.erb
<div class="container">

<h2>Novo projeto de lei</h2> <br />

	<div class="container">
		<%= render 'form', law_project: @law_project %>
	</div>

</div>

app/views/law_projects/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

	<%= form_with(model: @law_project, local: true) do |form| %>
		
		<% @law_project.politician_ids[0] = @law_project.politicians.first.name %>
	  <div class="row">
	    
	    <div class="col-md-4">
	      <div class="form-group">
	      	<h4>Projeto de lei - número</h4>
	        <%= form.number_field :law_number, id: :law_project_law_number, class: 'form-control', disabled: :true  %>
	      </div>
	    </div>

	    <div class="col-md-4">
	      <div class="form-group">
	        <h4>Autor</h4>
	        <%= form.text_field :politician_ids, id: :law_project_politician_ids, class: 'form-control', readonly: :true %>
	      </div>
	    </div>

	    <div class="col-md-4">
	      <div class="form-group">
	        <h4>Data</h4>
	        <%= form.text_field :date, id: :law_project_date, type: 'date', class: 'form-control', readonly: :true %>
	      </div>
	    </div>

	  </div>

	  <div class="row">
	    <div class="col-md-12">
	      <div class="form-group">
	        <h4>Resumo do projeto</h4>
	        <%= form.text_area :abstract, id: :law_project_abstract, class: 'form-control', readonly: :true %>
	      </div>
	    </div>
	  </div>


	  <div class="row">
	    <div class="col-md-12">
	      <div class="form-group">
	        <h4 >Texto original</h4> 
	        <span data-toggle="collapse" data-target="#collapseTextoOriginal" class="glyphicon glyphicon-chevron-right expand-law"></span>
	        
	        <div class="collapse" id="collapseTextoOriginal">
			  <div class="card card-block">
			    <%= form.text_area :description, id: :law_project_description, class: 'form-control', readonly: :true %>
			  </div>
			</div>
	      </div>
	    </div>
	  </div>
	<% end %>

	<%= link_to 'Editar', edit_law_project_path(@law_project) if (logged_in? && isAdmin?) %>
	<%= link_to 'Voltar', law_projects_path %> <br /> <br />

	
	<div class="container">
		<%= render 'acceptance_project' %>
	</div><hr />

	<div class="container">
		<%= render 'comment' if (!logged_in? || (logged_in? && !isAdmin?)) %>
	</div>

	<div class="container">
		<%= render 'all_comments' %>
	</div>
	

</div>

app/views/law_projects/users_index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

  <h2>Projetos de lei</h2><br />

  <div class="row">

    <% @law_projects.each do |lp| %>

      <div class="col-sm-6 col-md-4">

        <div class="thumbnail">

          <img src="/assets/law-image.jpeg" alt="projeto de lei">
          
          <div class="caption">
            
            <h3><%= lp.abstract %></h3>
            <a href="/politicians/<%=lp.politicians.first.id%>"><h5>Autor: <%= lp.politicians.first.name %></h5></a>
            
            <div class="acceptances-counter">

              <span class="badge badge-like">
                <%= lp.countAcceptances[lp.id][:acceptances][:like] %>
              </span> <span class="like-icon liked" aria-hidden="true"></span> 

              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              
              <span class="badge badge-dislike">
                <%= lp.countAcceptances[lp.id][:acceptances][:dislike] %> 
              </span> <span class="dislike-icon disliked" aria-hidden="true"></span>

            </div>

            <p><a href="/law_projects/<%=lp.id%>" class="btn btn-default" role="button">Visualizar projeto</a></p>

          </div>

        </div>

      </div>

    <% end %>

  </div>

</div>