config/routes.rb
Rails.application.routes.draw do
  
  resources :parties
  get 'sessions/new'

  get '/home' => 'home#index'
  
  get '/ranking' => 'ranking#index'
  get '/curtidas' => 'ranking#loadGraphic'
  get '/espectro' => 'users#politicSpectre'
  get 'ranking/data', :defaults => { :format => 'json' }

  post '/like' => 'acceptances#acceptancesInterceptor'
  post '/update-comment' => 'comments#updateComment'

  post '/generate-colors' => 'ranking#generateColorsToSequencesGraph'

  root 'home#index'

  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'

  get '/projeto' => 'home#o_projeto'
  get '/projeto/esquerda-direita' => 'home#esquerda_direita'
  get '/projeto/espectro-politico' => 'home#espectro_politico'

  get '/projetos-de-lei' => 'law_projects#index'
  get '/deputados' => 'politicians#index'

  get '/alterar-senha' => 'users#show_change_password'
  post '/change-password' => 'users#change_password'

  resources :comments
  resources :acceptances
  resources :interactions
  resources :notices
  resources :experiences
  resources :states
  resources :charges
  resources :politicians
  resources :law_projects
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/experience.rb
class Experience < ApplicationRecord
	belongs_to :politician
	
	validates :title, presence:true
    validates :init_year, presence:true, length: { is: 4 }
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :filterAccess
  before_action :set_experience, only: [:show, :edit, :update, :destroy]

  # GET /experiences
  # GET /experiences.json
  def index
    @experiences = Experience.all
  end

  # GET /experiences/1
  # GET /experiences/1.json
  def show
  end

  # GET /experiences/new
  def new
    @experience = Experience.new
  end

  # GET /experiences/1/edit
  def edit
  end

  # POST /experiences
  # POST /experiences.json
  def create
    @experience = Experience.new(experience_params)

    respond_to do |format|
      if @experience.save
        format.html { redirect_to @experience, notice: 'Experience was successfully created.' }
        format.json { render :show, status: :created, location: @experience }
      else
        format.html { render :new }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiences/1
  # PATCH/PUT /experiences/1.json
  def update
    respond_to do |format|
      if @experience.update(experience_params)
        format.html { redirect_to @experience, notice: 'Experience was successfully updated.' }
        format.json { render :show, status: :ok, location: @experience }
      else
        format.html { render :edit }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiences/1
  # DELETE /experiences/1.json
  def destroy
    @experience.destroy
    respond_to do |format|
      format.html { redirect_to experiences_url, notice: 'Experience was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def filterAccess
    redirect_to "/" unless (!current_user.nil? && isAdmin?)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experience
      @experience = Experience.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experience_params
      params.require(:experience).permit(:title, :init_year, :end_year)
    end
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/_form.html.erb
<%= form_with(model: experience, local: true) do |form| %>
  <% if experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
      <% experience.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :experience_title %>
  </div>

  <div class="field">
    <%= form.label :init_year %>
    <%= form.number_field :init_year, id: :experience_init_year %>
  </div>

  <div class="field">
    <%= form.label :end_year %>
    <%= form.number_field :end_year, id: :experience_end_year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/experiences/edit.html.erb
<h1>Editing Experience</h1>

<%= render 'form', experience: @experience %>

<%= link_to 'Show', @experience %> |
<%= link_to 'Back', experiences_path %>

app/views/experiences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Experiences</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Init year</th>
      <th>End year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @experiences.each do |experience| %>
      <tr>
        <td><%= experience.title %></td>
        <td><%= experience.init_year %></td>
        <td><%= experience.end_year %></td>
        <td><%= link_to 'Show', experience %></td>
        <td><%= link_to 'Edit', edit_experience_path(experience) %></td>
        <td><%= link_to 'Destroy', experience, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Experience', new_experience_path %>

app/views/experiences/new.html.erb
<h1>New Experience</h1>

<%= render 'form', experience: @experience %>

<%= link_to 'Back', experiences_path %>

app/views/experiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @experience.title %>
</p>

<p>
  <strong>Init year:</strong>
  <%= @experience.init_year %>
</p>

<p>
  <strong>End year:</strong>
  <%= @experience.end_year %>
</p>

<%= link_to 'Edit', edit_experience_path(@experience) %> |
<%= link_to 'Back', experiences_path %>